name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: pokeport

jobs:
  build-project:
    name: build pokeport
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pokeport
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (server)
        run: npm install
        working-directory: pokeport/server

      - name: Build frontend
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          POKEMON_TCGAPI_KEY: ${{ secrets.POKEMON_TCGAPI_KEY }}
        run: npm run build

      # Do NOT run the server here; IONOS will start it after deployment

      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: c27592f1-e993-44d6-a9d8-a0e2d7bb60b3
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: pokeport
          config-file: pokeport/.deploy-now/config.yaml
          action: upload
